joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint_one
    - arm_joint_two
    - arm_joint_three
    - arm_joint_four
  gains:
    arm_joint_one:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_two:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_three:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_four:
      p: 100
      d: 1
      i: 1
      i_clamp: 1