controller_list:
  - name: joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_one
      - arm_joint_two
      - arm_joint_three
      - arm_joint_four